import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SiGitbook } from "react-icons/si";
import { Cairo_Play } from "next/font/google"; // Import Cairo Play properly
import "./globals.css";

// Import Geist Sans and Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Import Cairo Play font
const cairoPlay = Cairo_Play({
  variable: "--font-cairo-play",
  subsets: ["latin"],
  weight: ["200", "400", "600", "800", "1000"], // Specify desired font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairoPlay.variable} antialiased h-screen scroll-smooth`}
      >
        <nav className="flex justify-around items-center w-full shadow-lg h-20">
          <div>
            <img src="/images/Infinite Logo.png" alt="Logo" width={120} height={20} className="" />
          </div>
          <div className="flex justify-center items-center gap-4">
            <a href="#home" className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500">Home</a>
            <a href="#about" className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500">About us</a>
            <a href="#ecosystem" className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500">Ecosystem</a>
            <a href="#roadmap" className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500">Roadmap</a>
            <a href="#team_section" className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500">Our team</a>
            <a href="https://infinite-sprouts.gitbook.io/infinite-sprout" className="flex justify-center items-center gap-1 px-4 py-2 font-bold border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><SiGitbook className="text-xl" />Git Book</a>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
