import type { Metadata } from "next";
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import { SiGitbook } from "react-icons/si";
import { Cairo_Play } from "next/font/google"; // Import Cairo Play properly
import "./globals.css";

// Import Geist Sans and Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Import Cairo Play font
const cairoPlay = Cairo_Play({
  variable: "--font-cairo-play",
  subsets: ["latin"],
  weight: ["200", "400", "600", "800", "1000"], // Specify desired font weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cairoPlay.variable} antialiased h-screen scroll-smooth`}
      >
        <nav className="flex justify-around items-center w-full opacty-0.4 shadow-lg h-20">
          <div>
            <img src="/images/Infinite Logo.png" alt="Logo" width={120} height={20} className="" />
          </div>
          <div className="flex justify-center items-center gap-4">
            <span className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><a href="#home">Home</a></span>
            <span className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><a href="#about">About us</a></span>
            <span className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><a href="#ecosystem">Ecosystem</a></span>
            <span className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><a href="#roadmap">Roadmap</a></span>
            <span className="px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><a href="#team_section">Our team</a></span>
            <span className="flex justify-center items-center gap-1 px-4 py-2 border border-black-600 rounded-lg hover:border-green-200 hover:scale-110 ease-out duration-500"><SiGitbook className="text-xl" /><a href="#team_section" className="font-bold">Git Book</a></span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
